fix(strings): Handle Unicode decoding errors instead of crashing (#1922)
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 853: invalid start byte
```