fix: strings -n 3 args passing
It was passed as `"-n 3"` instead of `"-n", "3"`.

Yielded the error:
```
CalledProcessError: Command '['strings', '-n 3', 'lib.so']' returned
non-zero exit status 1.

error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strings: unknown flag: -n 3
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strings [-] [-a] [-o] [-t format] [-number] [-n number] [[-arch <arch_flag>] ...] [--] [file ...]
```