fix: set packaging minimum version
Set packaging minimum version to 22.0 to avoid the following error with
setuptools 71.x:

TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'

Likelihood of encountering this error increased since commit
e4239bd3b838b1717e295412113030ee42631fc6 which bumped minimum version of
setuptools from 65.5.1 to 70.0.0

More information:
 - https://github.com/pypa/setuptools/issues/4483
 - https://github.com/pypa/setuptools/issues/4501

Signed-off-by: Fabrice Fontaine <fabrice.fontaine@orange.com>